# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Must be synced with pyproject.toml
    rev: v0.4.10
    hooks:
    -   id: ruff
        args: [--fix, --force-exit]
    -   id: ruff-format
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
