name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.1.0, v1.2.3, etc.

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install UV and setup Python
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.11'
        enable-cache: true
        cache-dependency-glob: "pyproject.toml uv.toml"

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      # Use GitHub Actions OIDC token for trusted publishing
      # https://docs.astral.sh/uv/guides/package/#publishing-your-package
      run: uv publish dist/*
