name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.1.0, v1.2.3, etc.

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: publish # Use the 'publish' environment

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install UV and setup Python
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.11'
        enable-cache: false

    - name: Install dependencies
      run: |
        uv pip install build wheel setuptools
        uv pip install -e .

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      run: uv publish --token ${{ secrets.PYPI_API_TOKEN }} dist/*
