name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.1.0, v1.2.3, etc.

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      env:
        UV_BOOTSTRAP_SKIP_MODIFY_PATH: 1

    - name: Set up virtual environment and Build Tools
      run: |
        # Add uv to the PATH
        export PATH="$HOME/.cargo/bin:$PATH"
        # Create venv
        uv venv .venv
        # Activate venv
        source .venv/bin/activate
        # Install build dependencies
        uv pip install build poetry-core

    - name: Build package with uv
      run: |
        # Add uv to the PATH
        export PATH="$HOME/.cargo/bin:$PATH"
        # Activate venv
        source .venv/bin/activate
        # Build the package
        uv build

    - name: Publish to PyPI with uv
      env:
        # Use Twine standard environment variables for uv publish
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        # Add uv to the PATH
        export PATH="$HOME/.cargo/bin:$PATH"
        # Activate venv
        source .venv/bin/activate
        # Publish the built distributions
        uv publish dist/*
